### ISSUE TITLE
Centralised constants

### ISSUE THREAD

**Issue by thmsrmbld** [bsassoli/milan_culture_map#10]
In this file: https://github.com/bsassoli/milan_culture_map/blob/main/venues/views.py

You have a data structure within a view:

```
icons = {
        'Museo': {
            'icon': 'university',
            'prefix': 'fa',
            'color': 'cadetblue'
        },
}
```

It's not common to store structure like this, but rather within a separate, centralised files like `constants.py` or `const.py`.

This means you can then do:

`from .constants import ICONS
`

Then you can use just ICONS in your view.

This keeps your view logic cleaner and your data structures easier to reason within.

From a personal project:

![Screenshot 2021-04-08 at 12 36 41](https://user-images.githubusercontent.com/3659224/114020081-18334a00-9867-11eb-84cd-7d06f84fa7d2.png)

I just import these wherever I need them - a single source of truth and clean view layers.

**Comment by bsassoli** [comment]
Actually this is _exactly_ the kind of things I need help with as a novice. So thank you, again! I was also thinking of creating a 'Marker' model with ForeignKey category. Would that be more elegant?

**Comment by thmsrmbld** [comment]
Almost certainly. Anything you can store in the DB with a FK relationship is always *super* useful from a management and query perspective. You could even have a Marker model that has an FK from an Icon model too - some of my projects have 7 or 8 layers of FK relationships.
