### ISSUE TITLE
Complex map view can be refactored for better organisation

### ISSUE THREAD

**Issue by thmsrmbld** [bsassoli/milan_culture_map#14]
So, the map function for this - this is quite complex:

https://github.com/bsassoli/milan_culture_map/blob/main/venues/views.py

Django philosophy is 'Fat Models, Skinny Views'. I try to write views with almost zero logic in them, and abstract the logic out to either:

- Model methods (https://docs.djangoproject.com/en/3.1/topics/db/models/#model-methods)
- Helper funcs (utils.py, etc)

There is a *lot* of logic in this view - I am sure it works well, so thats great! But from a maintainability perspective, and for the future, you want to consider implementing all this logic *outside* of your views and just call it in when you need it.

Future you will thank you for this 😄

**Comment by bsassoli** [comment]
Of course. Will do. It's clearly nonsense to not have it as a helper.
