### ISSUE TITLE
.env variables

### ISSUE THREAD

**Issue by thmsrmbld** [bsassoli/milan_culture_map#8]
I don't know how you plan to deploy this  - but it's worth knowing that there are a number of ways to manage settings.py files in production and locally.

My preference is to have two .env files - each for local or production. This means in your settings you can just get any sensitive details from an .env file, rather than have it hard coded in your settings file, and it makes it more portable too.

These are all things you want to reference from variables in .env files:

```
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's7bd592!zcpn+$v6#9u1c2yurz^0i_&=_#3!6#3c=tm&+$b%-9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
```

**Comment by bsassoli** [comment]
Yes, I would have done it in a second time - I still have to learn how to export viable to the environment.

**Comment by thmsrmbld** [comment]
You can use `SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")` and then in your .env file:

`DJANGO_SECRET_KEY=ajhfskdjfhsdfgjshdgfsdjh`
